spring:
  application:
    name: BidWave
  main:
    web-application-type: servlet
    banner-mode: console
  banner:
    location: banner/banner.txt
  datasource:
    url: jdbc:mysql://localhost:3306/bidwave?useSSL=false&serverTimezone=UTC
    username: root
    password: 0000
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9191

mybatis:
  type-aliases-package: com.bidwave.dto


logging:
  level:
    root: INFO
    com.bidwave: DEBUG
